/**
 * strings.ts
 *
 * Typisierte String-Map für die App language (CONTEXT.md, Grill 2026-07-24):
 * Deutsch + Englisch, bewusst OHNE i18n-Framework — bei zwei Locales wären
 * Pluralregeln und Lazy-Loading nur Ballast. `en` ist die Quelle der Typen;
 * `de: Strings` zwingt per Compiler dazu, dass jede neue UI-Zeile in beiden
 * Sprachen existiert. Strings mit Einsetzwerten sind Funktionen.
 *
 * Nicht hierüber laufen: die Sprach-Labels selbst ("English"/"Deutsch",
 * appLanguage.ts — immer in der eigenen Sprache), Modell-Namen, Thinking
 * quotes (Inhalt, kein Chrome) und Backend-Fehlertexte (V1-Scope-Cut).
 */

import { getAppLanguage, useAppLanguage, type AppLanguage } from './appLanguage';
import type { ChatGroupLabel } from './components/Sidebar/groupChatsByDate';

const en = {
  settings: {
    title: 'Settings',
    close: 'Close',
    loading: 'Loading settings…',
    tabs: {
      appearance: 'Appearance',
      model: 'Model',
      language: 'Language',
      instructions: 'Instructions',
    },
    activeModelDot: 'Active model configuration',
    appearance: {
      theme: 'Theme',
      note: 'Themes apply instantly — no activation needed.',
    },
    language: {
      appLanguage: 'App language',
      note: 'Applies instantly to the interface, automatic messages — like the prompt that creates the Video overview — and Explain answers.',
      howTitle: 'How language works',
      howNote: 'Chat replies mirror the language of your own message — ask in English, get English. The app language only sets what Syflo writes on its own.',
      dictation: 'Dictation',
      dictationBadge: 'Automatic · German + English',
      dictationNote: 'Detects the spoken language on its own — mixed sentences included. There is nothing to configure.',
    },
    instructions: {
      label: 'Custom instructions',
      switchAria: 'Apply custom instructions',
      switchOnTitle: 'Applied to every chat reply',
      switchOffTitle: 'Turned off — the text stays saved',
      placeholder: 'e.g. After every answer, correct the German in my message and list new vocabulary with articles.',
      note: 'Sent with every chat reply in all chat trees; your instructions take precedence over the built-in style rules. Explain, chat titles and summaries are not affected. The switch turns them off without deleting the text.',
    },
    model: {
      stepProvider: 'Provider',
      stepModel: 'Model',
      stepModels: 'Models',
      stepApiKey: 'API Key',
      ollamaLabel: 'Ollama (local)',
      openaiLabel: 'OpenAI (Cloud)',
      costFree: 'Free',
      costPaid: 'Pay per use',
      activeBadge: 'Active',
      activeTitle: 'Currently in use',
      keySaved: 'saved',
      keyPlaceholderSet: '••••••••••  (overwrite)',
      keyPlaceholderEmpty: 'sk-…',
      keyShow: 'Show API key',
      keyHide: 'Hide API key',
      keyRemove: 'Remove',
      keyNote: 'The key is stored only in the local backend and is never sent back to the frontend.',
      guideTitle: "Don't have an API key yet?",
      guideBody: "You'll need a free OpenAI account and a $5 starter balance. Creating the key takes about a minute.",
      guideCta: 'Get your API key',
      guideWhat: 'What $5 gets you',
      guideMiniMessages: '~10,000 messages',
      guide4oMessages: '~500 messages',
      guidePricing: 'Full pricing',
      refreshList: 'Refresh model list',
      machineBanner: (gb: number) => `This machine: ${gb} GB memory — recommended:`,
      rowRecommended: 'Recommended for this machine',
      rowInstalled: 'Installed',
      rowNotInstalled: 'Not installed',
      rowCanThink: ' · can think',
      download: 'Download',
      removeModelTitle: 'Remove model',
      removeModelAria: (name: string) => `Remove ${name}`,
      ollamaUnreachable: "Ollama isn't reachable at localhost:11434 — start it to manage your local models.",
      libraryNote: 'The active model is switched from the chat composer. Models run on your machine — nothing leaves your computer.',
      installOllama: 'Install Ollama',
      downloadFailed: 'Download failed',
      removeFailed: 'Failed to remove model',
    },
    footer: {
      activated: 'Activated',
      needsKey: 'Add an API key to activate OpenAI',
      clickActivate: 'Click Activate to apply your selection',
      selectionActive: 'Current selection is active',
      saved: 'Saved',
      clickSave: 'Click Save to apply your changes',
      instructionsOn: 'Applied to every chat reply',
      instructionsOff: 'Instructions are off',
      save: 'Save',
      saving: 'Saving…',
      activate: 'Activate',
      activating: 'Activating…',
      saveTitleDirty: 'Save and apply these instructions',
      saveTitleClean: 'No changes to save',
      activateTitleNeedsKey: 'Enter an OpenAI API key first',
      activateTitleClean: 'No changes to activate',
      activateTitleDirty: 'Apply and activate this configuration',
    },
    errors: {
      saveFailed: 'Failed to save settings',
      saveInstructionsFailed: 'Failed to save instructions',
      removeKeyFailed: 'Failed to remove API key',
    },
  },
  chatArea: {
    emptyTitle: 'How can I help you today?',
    emptySubtitle: 'Select a chat from the sidebar or start a new one.',
    toggleHighlightsTitle: 'Show all highlights of this tree',
    highlightsButton: 'Highlights',
    branchedFrom: 'Branched from ',
    showLess: 'Show less',
    showFullText: 'Show full text',
    emptyChatTitle: 'Start the conversation',
    emptyChatHint: 'Right-click any word in a response to get a definition or branch a new chat.',
    scrollToLatest: 'Scroll to latest',
    dropFiles: 'Drop files to attach',
    attachmentsHeading: 'Attachments',
    quoteFrom: (label: string) => `from "${label}"`,
    removeQuote: 'Remove quote',
    attach: 'Attach',
    menuMedia: 'Media',
    menuPdf: 'PDF',
    menuResearchPaper: 'Research paper',
    menuYouTubeTranscript: 'YouTube Transcript',
    placeholderAsk: 'Ask anything',
    placeholderAskQuote: 'Ask about this…',
    transcribing: 'Transcribing…',
    startRecording: 'Start recording',
    stopRecording: 'Stop recording',
    stopResponse: 'Stop response',
    send: 'Send',
  },
  messageBubble: {
    thinking: 'Thinking…',
    thoughtFor: (duration: string) => `Thought for ${duration}`,
    thoughts: 'Thoughts',
    interrupted: 'Interrupted',
    failed: 'The answer could not be generated.',
    retry: 'Try again',
    // Prefill-ETA (design/mockup-prefill-progress.html §01): ehrliche
    // Schätzung, deshalb immer mit "~"; bei Überziehung kein fake 99 %.
    prefillReading: (s: number) => `Reading the source… ~${s} s left`,
    prefillLonger: 'Reading the source… taking a bit longer',
    queuedNext: 'Waiting — up next',
    queued: (ahead: number) =>
      ahead === 1 ? 'Waiting — 1 request ahead' : `Waiting — ${ahead} requests ahead`,
    sources: 'Sources',
    assistantThinking: 'Assistant is thinking',
    tipLabel: 'Tip: ',
  },
  attachmentChip: {
    renameAlias: 'Rename alias',
    remove: 'Remove',
    clickToRename: (alias: string) => `${alias} — click to rename`,
  },
  questionNav: {
    buttonLabel: (n: number) => `${n} questions`,
    buttonTitle: 'All questions in this chat',
    popoverHeading: 'Questions in this chat',
    previous: 'Previous question (Alt+↑)',
    next: 'Next question (Alt+↓)',
  },
  sidebar: {
    expand: 'Expand sidebar',
    collapse: 'Collapse sidebar',
    newChat: 'New Chat',
    settings: 'Settings',
    openSettings: 'Open settings',
    switchToMindMap: 'Switch to Mind Map',
    switchToChat: 'Switch to Chat',
    rename: 'Rename',
    delete: 'Delete',
    deleteChatTitle: 'Delete chat?',
    deleteChatBody: (title: string) => `"${title}" and all its branched chats will be permanently removed.`,
    deleteFailed: 'Could not delete the chat. Is the backend running?',
    cancel: 'Cancel',
    deleting: 'Deleting…',
    retry: 'Retry',
    noChats: 'No chats yet',
    allChats: 'All chats',
    responseInProgress: 'Response in progress',
    queuedInQueue: 'Question waiting in queue',
    // Anzeige-Texte der Datums-Gruppen — groupChatsByDate.ts liefert die
    // Labels als stabile Schlüssel, übersetzt wird erst beim Rendern.
    groups: {
      'Today': 'Today',
      'Yesterday': 'Yesterday',
      'This week': 'This week',
      'Last week': 'Last week',
      'This month': 'This month',
      'Older': 'Older',
    } satisfies Record<ChatGroupLabel, string>,
  },
  videoBanner: {
    transcriptAttached: ' · transcript attached',
    viewTranscript: 'View transcript',
    openOnYouTube: 'Open on YouTube',
  },
  transcriptDrawer: {
    title: 'Transcript',
    close: 'Close transcript',
    sourceNote: 'This is the source text the model reads.',
    languageNote: (lang: string) => ` Language: ${lang}.`,
  },
  paperSearch: {
    title: 'Add a research paper',
    close: 'Close',
    subtitle: 'The imported PDF is attached to this chat.',
    placeholder: 'Search by title, author or topic…',
    search: 'Search',
    rateLimited: 'Search services are rate-limiting us. Wait a moment, then try again.',
    searching: 'Searching arXiv and OpenAlex…',
    noResults: 'No results.',
    cites: (count: string) => ` · ${count} cites`,
    openAccess: 'Open access',
    manualDownload: 'Manual download',
    paywalled: 'Paywalled',
    importButton: 'Import',
    importing: 'Importing…',
    openSourcePage: 'Open source page',
    manualHint: 'host blocks direct download — upload the PDF after saving it',
    viewPublisher: 'View publisher',
    noPdf: 'no PDF',
    searchFailed: 'Search failed',
    importFailed: 'Import failed',
  },
  youtubeSearch: {
    title: 'Add a YouTube transcript',
    close: 'Close',
    subtitle: "The transcript becomes this tree's source; the video itself is never downloaded.",
    placeholder: 'Search YouTube…',
    search: 'Search',
    searching: 'Searching YouTube…',
    noResults: 'No results.',
    add: 'Add',
    fetching: 'Fetching…',
    searchFailed: 'Search failed',
    importFailed: 'Import failed',
  },
  highlightsDrawer: {
    title: 'Highlights',
    close: 'Close highlights',
    all: 'All',
    empty: 'No highlights yet — select text and right-click to highlight.',
    pdfSource: (page: number) => `PDF · p. ${page}`,
    chatSource: (title: string) => `Chat · ${title}`,
    // Locale der Datumsformatierung — folgt der App language.
    dateLocale: 'en-US',
  },
  modelPicker: {
    switchModel: (name: string) => `Switch model (${name})`,
    recommended: 'Recommended for this Mac',
    installedWithSize: (size: string) => `${size} · installed`,
    installed: 'Installed',
    recommendHint: (name: string) => `${name} is recommended for this Mac`,
    downloadInSettings: 'Download it in Settings',
    thinking: 'Thinking',
    on: 'On',
    off: 'Off',
    manageModels: 'Manage models',
    ollamaRunning: 'Ollama · running locally',
    ollamaNotReachable: 'Ollama not reachable',
  },
  floatingPopup: {
    definition: 'Definition',
    wordCount: (n: number) => `· ${n} words`,
    collapse: 'Collapse',
    copyText: 'Copy text',
    copiedTitle: 'Copied!',
    copiedAria: 'Copied',
    close: 'Close',
    loadingDefinition: 'Loading definition…',
    renameColors: 'Rename colors',
    highlightColor: 'Highlight color',
    cancel: 'Cancel',
    renameLabels: 'Rename labels',
    resetToDefault: 'Reset to default',
    labelFor: (color: string) => `Label for ${color}`,
    highlightAs: (label: string) => `Highlight as ${label}`,
    saveLabels: 'Save labels',
    askInChat: 'Ask in chat',
    openAsNewChat: 'Open as new chat',
  },
  inheritedContext: {
    carries: (n: number) => `Carries background from ${n} earlier ${n === 1 ? 'chat' : 'chats'}`,
    hide: 'Hide',
    show: 'Show what the AI knows',
    inheritedWordForWord: 'inherited word-for-word',
    hideLiteral: 'Hide the literal text',
    showLiteral: 'Show the literal text the AI receives',
    parentFullText: 'The full conversation travels along word-for-word.',
    noSummaryYet: 'No summary yet — it is generated when you send the first message.',
    sentWithEvery: 'Sent to the AI with every message in this chat.',
  },
  parentContext: {
    badge: 'parent chat',
    openChat: 'Open this chat',
  },
  mindMap: {
    mainTopic: 'Main Topic',
    noChats: 'No chats yet',
  },
  app: {
    gpuWarning: (pct: number) =>
      `Model runs only ${pct}% on the GPU — responses will be much slower. Try a smaller model.`,
    newChatTitle: 'New Chat',
    aboutChatTitle: (word: string) => `About: ${word}`,
    newTreeTitle: 'This chat tree already has a source',
    newTreeLead: 'Each chat tree holds one source — a PDF or a YouTube transcript.',
    newTreeAskPrefix: 'Start a new tree with ',
    newTreeAskSuffix: '?',
    cancel: 'Cancel',
    startNewTree: 'Start new tree',
    noDefinition: '(No definition returned)',
    unknownError: 'Unknown error',
    couldNotLoadDefinition: (msg: string) => `Could not load definition: ${msg}`,
    couldNotCreateChat: (msg: string) => `Could not create chat: ${msg} — is the backend running?`,
    chatFallbackLabel: 'chat',
    resizeMindMap: 'Resize mind map',
    resizeChatColumn: 'Resize chat column',
  },
};

export type Strings = typeof en;

const de: Strings = {
  settings: {
    title: 'Einstellungen',
    close: 'Schließen',
    loading: 'Einstellungen werden geladen…',
    tabs: {
      appearance: 'Erscheinungsbild',
      model: 'Modell',
      language: 'Sprache',
      instructions: 'Anweisungen',
    },
    activeModelDot: 'Aktive Modell-Konfiguration',
    appearance: {
      theme: 'Farbschema',
      note: 'Farbschemata wirken sofort — keine Aktivierung nötig.',
    },
    language: {
      appLanguage: 'App-Sprache',
      note: 'Wirkt sofort auf die Oberfläche, automatische Nachrichten — etwa den Prompt, der die Video overview erzeugt — und Explain-Antworten.',
      howTitle: 'So funktioniert die Sprache',
      howNote: 'Chat-Antworten spiegeln die Sprache deiner eigenen Nachricht — wer auf Englisch fragt, bekommt Englisch. Die App-Sprache bestimmt nur, was Syflo von sich aus schreibt.',
      dictation: 'Diktat',
      dictationBadge: 'Automatisch · Deutsch + Englisch',
      dictationNote: 'Erkennt die gesprochene Sprache selbst — auch gemischte Sätze. Hier gibt es nichts einzustellen.',
    },
    instructions: {
      label: 'Eigene Anweisungen',
      switchAria: 'Eigene Anweisungen anwenden',
      switchOnTitle: 'Gilt für jede Chat-Antwort',
      switchOffTitle: 'Ausgeschaltet — der Text bleibt gespeichert',
      placeholder: 'z. B. Korrigiere nach jeder Antwort das Deutsch in meiner Nachricht und liste neue Vokabeln mit Artikel auf.',
      note: 'Wird mit jeder Chat-Antwort in allen Chat-Bäumen gesendet; deine Anweisungen haben Vorrang vor den eingebauten Stilregeln. Explain, Chat-Titel und Zusammenfassungen sind nicht betroffen. Der Schalter deaktiviert sie, ohne den Text zu löschen.',
    },
    model: {
      stepProvider: 'Provider',
      stepModel: 'Modell',
      stepModels: 'Modelle',
      stepApiKey: 'API-Schlüssel',
      ollamaLabel: 'Ollama (lokal)',
      openaiLabel: 'OpenAI (Cloud)',
      costFree: 'Kostenlos',
      costPaid: 'Nutzungsbasiert',
      activeBadge: 'Aktiv',
      activeTitle: 'Wird gerade verwendet',
      keySaved: 'gespeichert',
      keyPlaceholderSet: '••••••••••  (überschreiben)',
      keyPlaceholderEmpty: 'sk-…',
      keyShow: 'API-Schlüssel anzeigen',
      keyHide: 'API-Schlüssel verbergen',
      keyRemove: 'Entfernen',
      keyNote: 'Der Schlüssel wird nur im lokalen Backend gespeichert und nie ans Frontend zurückgeschickt.',
      guideTitle: 'Noch keinen API-Schlüssel?',
      guideBody: 'Du brauchst ein kostenloses OpenAI-Konto und 5 $ Startguthaben. Den Schlüssel zu erstellen dauert etwa eine Minute.',
      guideCta: 'API-Schlüssel holen',
      guideWhat: 'Was du für 5 $ bekommst',
      guideMiniMessages: '~10.000 Nachrichten',
      guide4oMessages: '~500 Nachrichten',
      guidePricing: 'Alle Preise',
      refreshList: 'Modell-Liste aktualisieren',
      machineBanner: (gb: number) => `Dieser Rechner: ${gb} GB Speicher — empfohlen:`,
      rowRecommended: 'Empfohlen für diesen Rechner',
      rowInstalled: 'Installiert',
      rowNotInstalled: 'Nicht installiert',
      rowCanThink: ' · kann denken',
      download: 'Herunterladen',
      removeModelTitle: 'Modell entfernen',
      removeModelAria: (name: string) => `${name} entfernen`,
      ollamaUnreachable: 'Ollama ist unter localhost:11434 nicht erreichbar — starte es, um deine lokalen Modelle zu verwalten.',
      libraryNote: 'Das aktive Modell wird im Chat-Eingabefeld gewechselt. Modelle laufen auf deinem Rechner — nichts verlässt deinen Computer.',
      installOllama: 'Ollama installieren',
      downloadFailed: 'Download fehlgeschlagen',
      removeFailed: 'Modell konnte nicht entfernt werden',
    },
    footer: {
      activated: 'Aktiviert',
      needsKey: 'Füge einen API-Schlüssel hinzu, um OpenAI zu aktivieren',
      clickActivate: 'Klicke auf Aktivieren, um deine Auswahl zu übernehmen',
      selectionActive: 'Aktuelle Auswahl ist aktiv',
      saved: 'Gespeichert',
      clickSave: 'Klicke auf Speichern, um deine Änderungen zu übernehmen',
      instructionsOn: 'Gilt für jede Chat-Antwort',
      instructionsOff: 'Anweisungen sind aus',
      save: 'Speichern',
      saving: 'Wird gespeichert…',
      activate: 'Aktivieren',
      activating: 'Wird aktiviert…',
      saveTitleDirty: 'Anweisungen speichern und anwenden',
      saveTitleClean: 'Keine Änderungen zu speichern',
      activateTitleNeedsKey: 'Zuerst einen OpenAI-API-Schlüssel eingeben',
      activateTitleClean: 'Keine Änderungen zu aktivieren',
      activateTitleDirty: 'Konfiguration übernehmen und aktivieren',
    },
    errors: {
      saveFailed: 'Einstellungen konnten nicht gespeichert werden',
      saveInstructionsFailed: 'Anweisungen konnten nicht gespeichert werden',
      removeKeyFailed: 'API-Schlüssel konnte nicht entfernt werden',
    },
  },
  chatArea: {
    emptyTitle: 'Wie kann ich dir heute helfen?',
    emptySubtitle: 'Wähle einen Chat in der Seitenleiste oder starte einen neuen.',
    toggleHighlightsTitle: 'Alle Highlights dieses Baums anzeigen',
    highlightsButton: 'Highlights',
    branchedFrom: 'Branch aus ',
    showLess: 'Weniger anzeigen',
    showFullText: 'Ganzen Text anzeigen',
    emptyChatTitle: 'Beginne das Gespräch',
    emptyChatHint: 'Rechtsklicke ein beliebiges Wort in einer Antwort für eine Definition — oder öffne einen neuen Branch.',
    scrollToLatest: 'Zur neuesten Nachricht springen',
    dropFiles: 'Dateien hier ablegen',
    attachmentsHeading: 'Anhänge',
    quoteFrom: (label: string) => `aus „${label}"`,
    removeQuote: 'Zitat entfernen',
    attach: 'Anhängen',
    menuMedia: 'Medien',
    menuPdf: 'PDF',
    menuResearchPaper: 'Research paper',
    menuYouTubeTranscript: 'YouTube Transcript',
    placeholderAsk: 'Frag irgendetwas',
    placeholderAskQuote: 'Frag etwas dazu…',
    transcribing: 'Transkribiert…',
    startRecording: 'Aufnahme starten',
    stopRecording: 'Aufnahme stoppen',
    stopResponse: 'Antwort stoppen',
    send: 'Senden',
  },
  messageBubble: {
    thinking: 'Denkt nach…',
    thoughtFor: (duration: string) => `Hat ${duration} nachgedacht`,
    thoughts: 'Gedanken',
    interrupted: 'Unterbrochen',
    failed: 'Die Antwort konnte nicht erzeugt werden.',
    retry: 'Erneut versuchen',
    prefillReading: (s: number) => `Quelle wird eingelesen… noch ~${s} s`,
    prefillLonger: 'Quelle wird eingelesen… dauert etwas länger',
    queuedNext: 'Wartet — als Nächstes dran',
    queued: (ahead: number) =>
      ahead === 1 ? 'Wartet — 1 Anfrage davor' : `Wartet — ${ahead} Anfragen davor`,
    sources: 'Quellen',
    assistantThinking: 'Der Assistent denkt nach',
    tipLabel: 'Tipp: ',
  },
  attachmentChip: {
    renameAlias: 'Alias umbenennen',
    remove: 'Entfernen',
    clickToRename: (alias: string) => `${alias} — zum Umbenennen klicken`,
  },
  questionNav: {
    buttonLabel: (n: number) => `${n} Fragen`,
    buttonTitle: 'Alle Fragen in diesem Chat',
    popoverHeading: 'Fragen in diesem Chat',
    previous: 'Vorherige Frage (Alt+↑)',
    next: 'Nächste Frage (Alt+↓)',
  },
  sidebar: {
    expand: 'Seitenleiste ausklappen',
    collapse: 'Seitenleiste einklappen',
    newChat: 'Neuer Chat',
    settings: 'Einstellungen',
    openSettings: 'Einstellungen öffnen',
    switchToMindMap: 'Zur Mind Map wechseln',
    switchToChat: 'Zum Chat wechseln',
    rename: 'Umbenennen',
    delete: 'Löschen',
    deleteChatTitle: 'Chat löschen?',
    deleteChatBody: (title: string) => `„${title}" und alle daraus entstandenen Branches werden endgültig entfernt.`,
    deleteFailed: 'Der Chat konnte nicht gelöscht werden. Läuft das Backend?',
    cancel: 'Abbrechen',
    deleting: 'Wird gelöscht…',
    retry: 'Erneut versuchen',
    noChats: 'Noch keine Chats',
    allChats: 'Alle Chats',
    responseInProgress: 'Antwort wird generiert',
    queuedInQueue: 'Frage wartet in der Warteschlange',
    groups: {
      'Today': 'Heute',
      'Yesterday': 'Gestern',
      'This week': 'Diese Woche',
      'Last week': 'Letzte Woche',
      'This month': 'Diesen Monat',
      'Older': 'Älter',
    },
  },
  videoBanner: {
    transcriptAttached: ' · Transcript angehängt',
    viewTranscript: 'Transcript ansehen',
    openOnYouTube: 'Auf YouTube öffnen',
  },
  transcriptDrawer: {
    title: 'Transcript',
    close: 'Transcript schließen',
    sourceNote: 'Das ist der Quelltext, den das Modell liest.',
    languageNote: (lang: string) => ` Sprache: ${lang}.`,
  },
  paperSearch: {
    title: 'Research paper hinzufügen',
    close: 'Schließen',
    subtitle: 'Das importierte PDF wird an diesen Chat angehängt.',
    placeholder: 'Nach Titel, Autor oder Thema suchen…',
    search: 'Suchen',
    rateLimited: 'Die Suchdienste bremsen uns gerade aus — warte einen Moment und versuch es dann erneut.',
    searching: 'Suche in arXiv und OpenAlex…',
    noResults: 'Keine Treffer.',
    cites: (count: string) => ` · ${count} Zitationen`,
    openAccess: 'Open Access',
    manualDownload: 'Manueller Download',
    paywalled: 'Paywall',
    importButton: 'Importieren',
    importing: 'Wird importiert…',
    openSourcePage: 'Quellseite öffnen',
    manualHint: 'Der Host blockiert den direkten Download — speichere das PDF und lade es dann hoch',
    viewPublisher: 'Zum Verlag',
    noPdf: 'kein PDF',
    searchFailed: 'Suche fehlgeschlagen',
    importFailed: 'Import fehlgeschlagen',
  },
  youtubeSearch: {
    title: 'YouTube transcript hinzufügen',
    close: 'Schließen',
    subtitle: 'Das Transcript wird zur Quelle dieses Baums; das Video selbst wird nie heruntergeladen.',
    placeholder: 'YouTube durchsuchen…',
    search: 'Suchen',
    searching: 'Suche auf YouTube…',
    noResults: 'Keine Treffer.',
    add: 'Hinzufügen',
    fetching: 'Wird geholt…',
    searchFailed: 'Suche fehlgeschlagen',
    importFailed: 'Import fehlgeschlagen',
  },
  highlightsDrawer: {
    title: 'Highlights',
    close: 'Highlights schließen',
    all: 'Alle',
    empty: 'Noch keine Highlights — markiere Text und rechtsklicke, um zu highlighten.',
    pdfSource: (page: number) => `PDF · S. ${page}`,
    chatSource: (title: string) => `Chat · ${title}`,
    dateLocale: 'de-DE',
  },
  modelPicker: {
    switchModel: (name: string) => `Modell wechseln (${name})`,
    recommended: 'Empfohlen für diesen Mac',
    installedWithSize: (size: string) => `${size} · installiert`,
    installed: 'Installiert',
    recommendHint: (name: string) => `${name} wird für diesen Mac empfohlen`,
    downloadInSettings: 'In den Einstellungen herunterladen',
    thinking: 'Thinking',
    on: 'An',
    off: 'Aus',
    manageModels: 'Modelle verwalten',
    ollamaRunning: 'Ollama · läuft lokal',
    ollamaNotReachable: 'Ollama nicht erreichbar',
  },
  floatingPopup: {
    definition: 'Definition',
    wordCount: (n: number) => `· ${n} Wörter`,
    collapse: 'Einklappen',
    copyText: 'Text kopieren',
    copiedTitle: 'Kopiert!',
    copiedAria: 'Kopiert',
    close: 'Schließen',
    loadingDefinition: 'Definition wird geladen…',
    renameColors: 'Farben umbenennen',
    highlightColor: 'Highlight-Farbe',
    cancel: 'Abbrechen',
    renameLabels: 'Labels umbenennen',
    resetToDefault: 'Auf Standard zurücksetzen',
    labelFor: (color: string) => `Label für ${color}`,
    highlightAs: (label: string) => `Highlight als ${label}`,
    saveLabels: 'Labels speichern',
    // Domänenbegriff (CONTEXT.md) — bleibt auch im Deutschen englisch.
    askInChat: 'Ask in chat',
    openAsNewChat: 'Als neuen Chat öffnen',
  },
  inheritedContext: {
    carries: (n: number) =>
      n === 1
        ? 'Trägt Hintergrund aus einem früheren Chat'
        : `Trägt Hintergrund aus ${n} früheren Chats`,
    hide: 'Ausblenden',
    show: 'Zeigen, was die KI weiß',
    inheritedWordForWord: 'wörtlich geerbt',
    hideLiteral: 'Wörtlichen Text ausblenden',
    showLiteral: 'Wörtlichen Text zeigen, den die KI erhält',
    parentFullText: 'Das ganze Gespräch reist Wort für Wort mit.',
    noSummaryYet: 'Noch keine Zusammenfassung — sie entsteht mit deiner ersten Nachricht.',
    sentWithEvery: 'Wird mit jeder Nachricht in diesem Chat an die KI gesendet.',
  },
  parentContext: {
    badge: 'Elternchat',
    openChat: 'Diesen Chat öffnen',
  },
  mindMap: {
    mainTopic: 'Hauptthema',
    noChats: 'Noch keine Chats',
  },
  app: {
    gpuWarning: (pct: number) =>
      `Das Modell läuft nur zu ${pct} % auf der GPU — Antworten werden deutlich langsamer. Probier ein kleineres Modell.`,
    newChatTitle: 'Neuer Chat',
    aboutChatTitle: (word: string) => `Über: ${word}`,
    newTreeTitle: 'Dieser Chat-Baum hat bereits eine Quelle',
    newTreeLead: 'Jeder Chat-Baum hält genau eine Quelle — ein PDF oder ein YouTube transcript.',
    newTreeAskPrefix: 'Neuen Baum mit ',
    newTreeAskSuffix: ' starten?',
    cancel: 'Abbrechen',
    startNewTree: 'Neuen Baum starten',
    noDefinition: '(Keine Definition erhalten)',
    unknownError: 'Unbekannter Fehler',
    couldNotLoadDefinition: (msg: string) => `Definition konnte nicht geladen werden: ${msg}`,
    couldNotCreateChat: (msg: string) => `Chat konnte nicht erstellt werden: ${msg} — läuft das Backend?`,
    chatFallbackLabel: 'Chat',
    resizeMindMap: 'Mind-Map-Höhe anpassen',
    resizeChatColumn: 'Chat-Spalte anpassen',
  },
};

const ALL: Record<AppLanguage, Strings> = { en, de };

/** Re-rendert die Komponente beim Sprachwechsel mit (Hook-Variante). */
export function useStrings(): Strings {
  return ALL[useAppLanguage()];
}

/** Für Code außerhalb von React (Module, Event-Handler ohne Hook-Zugriff). */
export function getStrings(): Strings {
  return ALL[getAppLanguage()];
}
